Syslog                  yes
UMask                   002
Domain                  dalletek.live
KeyFile                 /etc/opendkim/keys/dalletek.live/mail.private
Selector                mail
Socket                  inet:8891@localhost
RequireSafeKeys         false
OversignHeaders         From
AutoRestart             yes
AutoRestartRate         10/1h
UserID                  opendkim
PidFile                 /var/run/opendkim/opendkim.pid
